package io.zheryc;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication
public class App extends Application {

    private static final String APP_TITLE = "Battle Junkie 5e";

    private ConfigurableApplicationContext springContext;
    private FXMLLoader fxmlLoader;

    private Parent rootNode;


    @Override
    public void init() {
        this.springContext = SpringApplication.run(App.class);
        fxmlLoader = new FXMLLoader();
        fxmlLoader.setControllerFactory(springContext::getBean);
    }

    @Override
    public void start(Stage stage) {
        stage.setTitle(APP_TITLE);

        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");

        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
        Scene scene = new Scene(new StackPane(l), 640, 480);
        stage.setScene(scene);
        stage.show();
//        stage.setTitle("JavaFX io.zheryc.App");
//
//        Stage stage2 = new Stage();
//        stage2.initModality(Modality.NONE);
//        stage2.initOwner(stage);
//        stage.show();
//
//        stage2.showAndWait();
    }

    @Override
    public void stop() {
        springContext.stop();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
